@extends('layout/main')

@section('content')
    <section class="main-content">
        <div class="container">
            <h1>News</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            voluptates
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            voluptatesLorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus alias nihil blanditiis aperiam ex? Libero accusantium omnis magnam dolore cupiditate perspiciatis quasi. Ipsum voluptates incidunt laboriosam at similique. Nulla, et.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos numquam, facere recusandae quas magni sequi et eveniet itaque aliquam dicta quae totam quia sint sapiente nihil! Perspiciatis eligendi at accusamus.
            </p>
        </div>
    </section>
    <div class="bar"></div>
@endsection